# Generated by Django 2.2.5 on 2019-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMSUSSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('networkCode', models.CharField(max_length=100)),
                ('serviceCode', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
