# Generated by Django 2.2.5 on 2019-09-06 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('Category', models.CharField(choices=[(1, 'Bakery and bread'), (2, 'Meat and sea food'), (3, 'Pasta and rice'), (4, 'Oils, sauces, salad dressings and condiments'), (5, 'cereals and breakfast foods'), (6, 'Soups and canned goods'), (7, 'Frozen foods'), (8, 'Dairy, chinese and eggs'), (9, 'Snacks and crackers'), (10, 'cerels and breakfast foods'), (11, 'Produce'), (12, 'Drinks')], max_length=100)),
                ('register_as', models.CharField(choices=[('item_key1', 'Farmer'), ('item_key2', 'Industry'), ('item_key3', 'Vendor/Merchant')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
