# Generated by Django 2.2.5 on 2019-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190909_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_as',
            field=models.CharField(max_length=20),
        ),
    ]
