# Generated by Django 2.2.5 on 2019-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190910_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_as',
            field=models.CharField(choices=[('item_key1', 'Farmer'), ('item_key2', 'Industry'), ('item_key3', 'Vendor/Merchant')], max_length=20),
        ),
    ]
