# Generated by Django 2.2.5 on 2019-09-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstock',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
