# Generated by Django 2.2.5 on 2019-09-30 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190912_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstock',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerStock', to=settings.AUTH_USER_MODEL),
        ),
    ]
